services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rustdata
    ports:
      - "5432:5432"
    volumes:
      - rustdata:/var/lib/postgresql/data

volumes:
  rustdata:
